-- TradeExecutor physical schema (PostgreSQL)
--
-- Idempotent: fresh databases get the full definitions from the CREATE TABLE
-- statements; databases carrying the earlier two-table stub are brought up to
-- the current data model by the ADD COLUMN IF NOT EXISTS / constraint blocks
-- below. The stub tables have never carried rows (the component has never run),
-- so ALTER COLUMN ... SET NOT NULL is safe.

CREATE SCHEMA IF NOT EXISTS trade_executor;

-- Durable record of every risk-evaluated decision, one row per consumed card.
CREATE TABLE IF NOT EXISTS trade_executor.t_trade_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thesis_card_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    exchange_code TEXT,
    action TEXT NOT NULL,
    quantity BIGINT,
    order_type TEXT,
    limit_price DOUBLE PRECISION,
    entry_price DOUBLE PRECISION,
    stop_price DOUBLE PRECISION,
    take_profit_price DOUBLE PRECISION,
    atr_20d DOUBLE PRECISION,
    risk_amount_usd DOUBLE PRECISION,
    confidence DOUBLE PRECISION,
    signal_strength DOUBLE PRECISION,
    source_analysis_ids JSONB,
    risk_check_passed BOOLEAN NOT NULL,
    risk_check_details TEXT,
    decided_at TIMESTAMPTZ NOT NULL
);

-- Bring the stub table up to the current model (no-ops on a fresh database).
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS thesis_card_id TEXT;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS exchange_code TEXT;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS entry_price DOUBLE PRECISION;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS stop_price DOUBLE PRECISION;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS take_profit_price DOUBLE PRECISION;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS atr_20d DOUBLE PRECISION;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS risk_amount_usd DOUBLE PRECISION;
ALTER TABLE trade_executor.t_trade_decisions ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION;
ALTER TABLE trade_executor.t_trade_decisions ALTER COLUMN thesis_card_id SET NOT NULL;

-- thesis_card_id UNIQUE is the idempotency guard against signal redelivery.
CREATE UNIQUE INDEX IF NOT EXISTS uq_trade_decisions_thesis_card
    ON trade_executor.t_trade_decisions (thesis_card_id);
CREATE INDEX IF NOT EXISTS ix_trade_decisions_instrument_decided
    ON trade_executor.t_trade_decisions (ticker, exchange_code, decided_at DESC);
CREATE INDEX IF NOT EXISTS ix_trade_decisions_passed
    ON trade_executor.t_trade_decisions (decided_at)
    WHERE risk_check_passed = TRUE;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_trade_decisions_action') THEN
        ALTER TABLE trade_executor.t_trade_decisions
            ADD CONSTRAINT ck_trade_decisions_action
            CHECK (action IN ('buy', 'sell', 'hold'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_trade_decisions_order_type') THEN
        ALTER TABLE trade_executor.t_trade_decisions
            ADD CONSTRAINT ck_trade_decisions_order_type
            CHECK (order_type IS NULL OR order_type IN ('market', 'limit'));
    END IF;
END$$;

-- One row per bracket leg (entry / stop / take_profit) for each decision.
CREATE TABLE IF NOT EXISTS trade_executor.t_trade_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id BIGINT NOT NULL REFERENCES trade_executor.t_trade_decisions(id),
    leg_role TEXT,
    ibkr_order_id BIGINT,
    ibkr_oca_group TEXT,
    status TEXT NOT NULL,
    fill_price DOUBLE PRECISION,
    fill_quantity BIGINT,
    commission DOUBLE PRECISION,
    executed_at TIMESTAMPTZ,
    error_message TEXT
);

ALTER TABLE trade_executor.t_trade_executions ADD COLUMN IF NOT EXISTS leg_role TEXT;
ALTER TABLE trade_executor.t_trade_executions ADD COLUMN IF NOT EXISTS ibkr_oca_group TEXT;

CREATE INDEX IF NOT EXISTS ix_trade_executions_decision
    ON trade_executor.t_trade_executions (decision_id);
CREATE INDEX IF NOT EXISTS ix_trade_executions_order
    ON trade_executor.t_trade_executions (ibkr_order_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_trade_executions_leg_role') THEN
        ALTER TABLE trade_executor.t_trade_executions
            ADD CONSTRAINT ck_trade_executions_leg_role
            CHECK (leg_role IS NULL OR leg_role IN ('entry', 'stop', 'take_profit'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_trade_executions_status') THEN
        ALTER TABLE trade_executor.t_trade_executions
            ADD CONSTRAINT ck_trade_executions_status
            CHECK (status IN ('submitted', 'filled', 'partial', 'rejected', 'cancelled'));
    END IF;
END$$;

-- Durable position state across the lifecycle; one open position per instrument.
CREATE TABLE IF NOT EXISTS trade_executor.t_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thesis_card_id TEXT NOT NULL,
    decision_id BIGINT NOT NULL REFERENCES trade_executor.t_trade_decisions(id),
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    side TEXT NOT NULL,
    quantity BIGINT NOT NULL,
    avg_entry_price DOUBLE PRECISION,
    stop_price DOUBLE PRECISION,
    take_profit_price DOUBLE PRECISION,
    time_exit_at TIMESTAMPTZ,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    realized_pnl DOUBLE PRECISION,
    exit_reason TEXT,
    CONSTRAINT ck_positions_side CHECK (side IN ('long', 'short')),
    CONSTRAINT ck_positions_exit_reason
        CHECK (exit_reason IS NULL
               OR exit_reason IN ('stop', 'take_profit', 'time', 'manual', 'invalidation'))
);

-- Enforce the one-open-position-per-instrument rule at the database level.
CREATE UNIQUE INDEX IF NOT EXISTS uq_positions_open_instrument
    ON trade_executor.t_positions (ticker, exchange_code)
    WHERE closed_at IS NULL;
-- Supports the time-exit scan for open positions past their holding window.
CREATE INDEX IF NOT EXISTS ix_positions_time_exit
    ON trade_executor.t_positions (time_exit_at)
    WHERE closed_at IS NULL;

-- Per-trading-day risk accounting backing the daily-loss kill-switch.
CREATE TABLE IF NOT EXISTS trade_executor.t_daily_risk (
    trade_date DATE PRIMARY KEY,
    realized_pnl DOUBLE PRECISION NOT NULL DEFAULT 0,
    trades_count INTEGER NOT NULL DEFAULT 0,
    halted BOOLEAN NOT NULL DEFAULT FALSE
);
