-- TradeExecutor physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS trade_executor;

CREATE TABLE IF NOT EXISTS trade_executor.t_trade_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    action TEXT NOT NULL,
    quantity BIGINT,
    order_type TEXT,
    limit_price DOUBLE PRECISION,
    signal_strength DOUBLE PRECISION,
    source_analysis_ids JSONB,
    risk_check_passed BOOLEAN NOT NULL,
    risk_check_details TEXT,
    decided_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS trade_executor.t_trade_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id BIGINT NOT NULL REFERENCES trade_executor.t_trade_decisions(id),
    ibkr_order_id BIGINT,
    status TEXT NOT NULL,
    fill_price DOUBLE PRECISION,
    fill_quantity BIGINT,
    commission DOUBLE PRECISION,
    executed_at TIMESTAMPTZ,
    error_message TEXT
);
