-- Shared physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS shared;

CREATE TABLE IF NOT EXISTS shared.t_api_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    endpoint TEXT,
    tokens_used BIGINT,
    cost_estimate DOUBLE PRECISION,
    called_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS shared.t_thesis_card_reviews (
    card_id TEXT PRIMARY KEY,
    decision_state TEXT NOT NULL,
    reviewed_by TEXT NOT NULL,
    review_reason TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_thesis_card_reviews_decision_state
        CHECK (decision_state IN ('approved', 'rejected'))
);

-- Drop old tables in reverse FK dependency order before recreating with new structure.
DROP TABLE IF EXISTS shared.t_watchlist_tickers CASCADE;
DROP TABLE IF EXISTS shared.t_exchange_listings CASCADE;
DROP TABLE IF EXISTS shared.t_instruments CASCADE;

CREATE TABLE IF NOT EXISTS shared.t_instruments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          TEXT UNIQUE,
    display_name  TEXT NOT NULL,
    aliases       TEXT[] NOT NULL DEFAULT '{}',
    identifiers   JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shared.t_exchange_listings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id BIGINT NOT NULL REFERENCES shared.t_instruments(id) ON DELETE CASCADE,
    ticker        TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    is_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ticker, exchange_code)
);
CREATE INDEX IF NOT EXISTS ix_exchange_listings_instrument
    ON shared.t_exchange_listings (instrument_id);

CREATE TABLE IF NOT EXISTS shared.t_watchlist_tickers (
    listing_id    BIGINT NOT NULL REFERENCES shared.t_exchange_listings(id) ON DELETE CASCADE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    source        TEXT NOT NULL DEFAULT 'manual',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (listing_id)
);

CREATE TABLE IF NOT EXISTS shared.t_instrument_lookup_cache (
    operation TEXT NOT NULL,
    target TEXT NOT NULL,
    provider TEXT NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    fetched_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (operation, target)
);
