-- Shared physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS shared;

CREATE TABLE IF NOT EXISTS shared.t_api_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    endpoint TEXT,
    tokens_used BIGINT,
    cost_estimate DOUBLE PRECISION,
    called_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS shared.t_thesis_card_reviews (
    card_id TEXT PRIMARY KEY,
    decision_state TEXT NOT NULL,
    reviewed_by TEXT NOT NULL,
    review_reason TEXT,
    reviewed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_thesis_card_reviews_decision_state
        CHECK (decision_state IN ('approved', 'rejected'))
);

CREATE TABLE IF NOT EXISTS shared.t_watchlist_tickers (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    source TEXT NOT NULL DEFAULT 'manual',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticker, exchange_code)
);

CREATE TABLE IF NOT EXISTS shared.t_instruments (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    display_name TEXT,
    identifiers JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticker, exchange_code)
);

CREATE TABLE IF NOT EXISTS shared.t_instrument_aliases (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    alias TEXT NOT NULL,
    alias_type TEXT NOT NULL DEFAULT 'alias',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticker, exchange_code, alias),
    CONSTRAINT fk_instrument_aliases_instrument
        FOREIGN KEY (ticker, exchange_code)
        REFERENCES shared.t_instruments (ticker, exchange_code)
        ON DELETE CASCADE
);
