-- ThesisBuilder physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS thesis_builder;

CREATE TABLE IF NOT EXISTS thesis_builder.t_news_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    sentiment DOUBLE PRECISION NOT NULL,
    relevance DOUBLE PRECISION NOT NULL,
    urgency TEXT NOT NULL,
    suggested_action TEXT NOT NULL,
    strategy TEXT,
    direction TEXT,
    event_type TEXT,
    subject_relation TEXT,
    price_impact_magnitude TEXT,
    impact_horizon TEXT,
    reasoning TEXT,
    confidence DOUBLE PRECISION NOT NULL,
    article_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    market_context_status TEXT,
    market_context_as_of TIMESTAMPTZ,
    market_context_snapshot JSONB,
    fundamentals_snapshot JSONB,
    is_market_moving BOOLEAN NOT NULL DEFAULT FALSE,
    content_type TEXT,
    validation_status TEXT NOT NULL DEFAULT 'valid',
    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    rejection_reason_code TEXT,
    llm_model TEXT NOT NULL,
    tokens_used BIGINT,
    analyzed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_news_analyses_confidence
        CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_news_analyses_relevance
        CHECK (relevance >= 0 AND relevance <= 1),
    CONSTRAINT ck_news_analyses_strategy
        CHECK (
            strategy IS NULL
            OR strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_news_analyses_direction
        CHECK (direction IS NULL OR direction IN ('buy', 'sell', 'hold')),
    CONSTRAINT ck_news_analyses_price_impact
        CHECK (price_impact_magnitude IS NULL OR price_impact_magnitude IN ('low', 'medium', 'high')),
    CONSTRAINT ck_news_analyses_impact_horizon
        CHECK (impact_horizon IS NULL OR impact_horizon IN ('intraday', '1d', '5d')),
    CONSTRAINT ck_news_analyses_subject_relation
        CHECK (
            subject_relation IS NULL
            OR subject_relation IN ('direct', 'supply_chain', 'customer_or_peer', 'macro_sector', 'none')
        ),
    CONSTRAINT ck_news_analyses_market_context_status
        CHECK (market_context_status IS NULL OR market_context_status IN ('fresh', 'delayed', 'stale', 'missing')),
    CONSTRAINT ck_news_analyses_validation_status
        CHECK (validation_status IN ('valid', 'rejected')),
    CONSTRAINT ck_news_analyses_content_type
        CHECK (content_type IS NULL OR content_type IN ('news_catalyst', 'opinion'))
);

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS exchange_code TEXT NOT NULL DEFAULT '';

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS strategy TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS direction TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS event_type TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS subject_relation TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS price_impact_magnitude TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS impact_horizon TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS fundamentals_snapshot JSONB;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS market_context_status TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS market_context_as_of TIMESTAMPTZ;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS market_context_snapshot JSONB;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS is_market_moving BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS validation_status TEXT NOT NULL DEFAULT 'valid';

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS rejection_reason_code TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS article_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS content_type TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    DROP CONSTRAINT IF EXISTS ck_news_analyses_content_type;

ALTER TABLE thesis_builder.t_news_analyses
    ADD CONSTRAINT ck_news_analyses_content_type
        CHECK (content_type IS NULL OR content_type IN ('news_catalyst', 'opinion'));

ALTER TABLE thesis_builder.t_news_analyses
    DROP CONSTRAINT IF EXISTS ck_news_analyses_impact_horizon;

ALTER TABLE thesis_builder.t_news_analyses
    ADD CONSTRAINT ck_news_analyses_impact_horizon
        CHECK (impact_horizon IS NULL OR impact_horizon IN ('intraday', '1d', '5d'));

ALTER TABLE thesis_builder.t_news_analyses
    DROP CONSTRAINT IF EXISTS ck_news_analyses_subject_relation;

ALTER TABLE thesis_builder.t_news_analyses
    ADD CONSTRAINT ck_news_analyses_subject_relation
        CHECK (
            subject_relation IS NULL
            OR subject_relation IN ('direct', 'supply_chain', 'customer_or_peer', 'macro_sector', 'none')
        );

ALTER TABLE thesis_builder.t_news_analyses
    DROP CONSTRAINT IF EXISTS t_news_analyses_article_id_fkey;

CREATE INDEX IF NOT EXISTS ix_news_analyses_article
    ON thesis_builder.t_news_analyses (article_id);

CREATE INDEX IF NOT EXISTS ix_news_analyses_instrument_analyzed
    ON thesis_builder.t_news_analyses (ticker, exchange_code, analyzed_at DESC);

CREATE INDEX IF NOT EXISTS ix_news_analyses_strategy_direction
    ON thesis_builder.t_news_analyses (ticker, exchange_code, strategy, direction, validation_status);

-- Opinion articles are retained for a future stock-analyst component to consume.
CREATE INDEX IF NOT EXISTS ix_news_analyses_opinion
    ON thesis_builder.t_news_analyses (analyzed_at DESC)
    WHERE content_type = 'opinion';

CREATE TABLE IF NOT EXISTS thesis_builder.t_message_processing_events (
    id BIGSERIAL PRIMARY KEY,
    source_message_id TEXT NOT NULL,
    event_id TEXT,
    article_id TEXT,
    outcome TEXT NOT NULL,
    reason_code TEXT,
    analyses_created INTEGER NOT NULL DEFAULT 0,
    signals_published INTEGER NOT NULL DEFAULT 0,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload_json JSONB,
    CONSTRAINT uq_message_processing_events_source_message
        UNIQUE (source_message_id),
    CONSTRAINT ck_message_processing_events_outcome
        CHECK (outcome IN ('analyzed', 'skipped', 'failed_dlq')),
    CONSTRAINT ck_message_processing_events_counts
        CHECK (analyses_created >= 0 AND signals_published >= 0)
);

CREATE INDEX IF NOT EXISTS ix_message_processing_events_processed_at
    ON thesis_builder.t_message_processing_events (processed_at DESC);

CREATE INDEX IF NOT EXISTS ix_message_processing_events_outcome_reason
    ON thesis_builder.t_message_processing_events (outcome, reason_code, processed_at DESC);

CREATE TABLE IF NOT EXISTS thesis_builder.t_evidence_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    strategy TEXT NOT NULL,
    direction TEXT,
    article_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    analysis_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    window_started_at TIMESTAMPTZ NOT NULL,
    last_evidence_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    status_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_evidence_windows_strategy
        CHECK (
            strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_evidence_windows_direction
        CHECK (direction IS NULL OR direction IN ('buy', 'sell', 'hold')),
    CONSTRAINT ck_evidence_windows_status
        CHECK (status IN ('collecting', 'satisfied', 'expired', 'rejected'))
);

ALTER TABLE thesis_builder.t_evidence_windows
    ADD COLUMN IF NOT EXISTS reprocess_run_id TEXT NULL;

ALTER TABLE thesis_builder.t_evidence_windows
    ADD COLUMN IF NOT EXISTS required_evidence_count INT NOT NULL DEFAULT 3;

CREATE INDEX IF NOT EXISTS ix_evidence_windows_instrument_status
    ON thesis_builder.t_evidence_windows (ticker, exchange_code, status, updated_at DESC);

DROP INDEX IF EXISTS thesis_builder.uq_evidence_windows_collecting;
CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_windows_collecting
    ON thesis_builder.t_evidence_windows (ticker, exchange_code, strategy, COALESCE(direction, ''), COALESCE(reprocess_run_id, ''))
    WHERE status = 'collecting';

CREATE INDEX IF NOT EXISTS ix_evidence_windows_expiry_scan
    ON thesis_builder.t_evidence_windows (status, window_started_at)
    WHERE status = 'collecting';

CREATE TABLE IF NOT EXISTS thesis_builder.t_thesis_cards (
    id TEXT PRIMARY KEY,
    idempotency_key TEXT NOT NULL UNIQUE,
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    direction TEXT NOT NULL,
    time_horizon TEXT NOT NULL,
    strategy TEXT NOT NULL,
    evidence JSONB NOT NULL,
    source_analysis_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence DOUBLE PRECISION NOT NULL,
    risk_max_loss_usd DOUBLE PRECISION NOT NULL,
    risk_stop_condition TEXT NOT NULL,
    risk_invalidation_condition TEXT NOT NULL,
    market_context_status TEXT,
    market_context_as_of TIMESTAMPTZ,
    market_context_snapshot JSONB,
    validation_status TEXT NOT NULL,
    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    rejection_reason_code TEXT,
    max_evidence_age_seconds DOUBLE PRECISION,
    allowed_max_evidence_age_seconds DOUBLE PRECISION,
    evidence_age_exceeded_seconds DOUBLE PRECISION,
    signal_published_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_thesis_cards_direction
        CHECK (direction IN ('buy', 'sell', 'hold')),
    CONSTRAINT ck_thesis_cards_strategy
        CHECK (
            strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_thesis_cards_confidence
        CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_thesis_cards_risk_max_loss
        CHECK (risk_max_loss_usd >= 0),
    CONSTRAINT ck_thesis_cards_market_context_status
        CHECK (market_context_status IS NULL OR market_context_status IN ('fresh', 'delayed', 'stale', 'missing')),
    CONSTRAINT ck_thesis_cards_validation_status
        CHECK (validation_status IN ('valid', 'rejected')),
    CONSTRAINT ck_thesis_cards_evidence_age_nonnegative
        CHECK (
            (max_evidence_age_seconds IS NULL OR max_evidence_age_seconds >= 0)
            AND (allowed_max_evidence_age_seconds IS NULL OR allowed_max_evidence_age_seconds >= 0)
            AND (evidence_age_exceeded_seconds IS NULL OR evidence_age_exceeded_seconds >= 0)
        )
);

ALTER TABLE thesis_builder.t_thesis_cards
    ADD COLUMN IF NOT EXISTS rejection_reason_code TEXT;

ALTER TABLE thesis_builder.t_thesis_cards
    ADD COLUMN IF NOT EXISTS max_evidence_age_seconds DOUBLE PRECISION;

ALTER TABLE thesis_builder.t_thesis_cards
    ADD COLUMN IF NOT EXISTS allowed_max_evidence_age_seconds DOUBLE PRECISION;

ALTER TABLE thesis_builder.t_thesis_cards
    ADD COLUMN IF NOT EXISTS evidence_age_exceeded_seconds DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS ix_thesis_cards_instrument_created
    ON thesis_builder.t_thesis_cards (ticker, exchange_code, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_thesis_cards_validation_expiry
    ON thesis_builder.t_thesis_cards (validation_status, expires_at);

CREATE INDEX IF NOT EXISTS ix_thesis_cards_stale_evidence
    ON thesis_builder.t_thesis_cards (created_at DESC)
    WHERE validation_status = 'rejected' AND rejection_reason_code = 'stale_evidence';

CREATE INDEX IF NOT EXISTS ix_thesis_cards_unpublished_valid
    ON thesis_builder.t_thesis_cards (created_at)
    WHERE validation_status = 'valid' AND signal_published_at IS NULL;

CREATE TABLE IF NOT EXISTS thesis_builder.t_card_synthesis_verdicts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_window_id BIGINT NOT NULL,
    card_id TEXT,
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    strategy TEXT NOT NULL,
    direction TEXT NOT NULL,
    verdict TEXT NOT NULL,
    reason_code TEXT,
    confidence DOUBLE PRECISION,
    llm_model TEXT NOT NULL,
    max_output_tokens INTEGER,
    response_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_card_synthesis_verdicts_verdict
        CHECK (verdict IN ('approve', 'reject', 'invalid', 'unavailable')),
    CONSTRAINT ck_card_synthesis_verdicts_confidence
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT ck_card_synthesis_verdicts_strategy
        CHECK (
            strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_card_synthesis_verdicts_direction
        CHECK (direction IN ('buy', 'sell', 'hold'))
);

CREATE INDEX IF NOT EXISTS ix_card_synthesis_verdicts_window
    ON thesis_builder.t_card_synthesis_verdicts (evidence_window_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_card_synthesis_verdicts_card
    ON thesis_builder.t_card_synthesis_verdicts (card_id)
    WHERE card_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS thesis_builder.t_reprocess_runs (
    run_id TEXT PRIMARY KEY,
    days_back INT NOT NULL,
    max_articles INT,
    status TEXT NOT NULL,
    articles_found INT,
    analyses_created INT,
    cards_created INT,
    error_code TEXT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    CONSTRAINT ck_reprocess_runs_status
        CHECK (status IN ('accepted', 'running', 'completed', 'failed')),
    CONSTRAINT ck_reprocess_runs_days_back
        CHECK (days_back >= 1)
);

-- Concurrency guard: at most one accepted/running reprocess run at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_reprocess_runs_active
    ON thesis_builder.t_reprocess_runs ((TRUE))
    WHERE status IN ('accepted', 'running');

CREATE INDEX IF NOT EXISTS ix_reprocess_runs_requested
    ON thesis_builder.t_reprocess_runs (requested_at DESC);
