-- ThesisBuilder physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS thesis_builder;

CREATE TABLE IF NOT EXISTS thesis_builder.t_news_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id TEXT NOT NULL REFERENCES news_fetcher.t_news_articles(id),
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    sentiment DOUBLE PRECISION NOT NULL,
    relevance DOUBLE PRECISION NOT NULL,
    urgency TEXT NOT NULL,
    suggested_action TEXT NOT NULL,
    strategy TEXT,
    direction TEXT,
    event_type TEXT,
    price_impact_magnitude TEXT,
    reasoning TEXT,
    confidence DOUBLE PRECISION NOT NULL,
    market_context_status TEXT,
    market_context_as_of TIMESTAMPTZ,
    market_context_snapshot JSONB,
    validation_status TEXT NOT NULL DEFAULT 'valid',
    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    rejection_reason_code TEXT,
    llm_model TEXT NOT NULL,
    tokens_used BIGINT,
    analyzed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_news_analyses_confidence
        CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_news_analyses_relevance
        CHECK (relevance >= 0 AND relevance <= 1),
    CONSTRAINT ck_news_analyses_strategy
        CHECK (
            strategy IS NULL
            OR strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_news_analyses_direction
        CHECK (direction IS NULL OR direction IN ('buy', 'sell', 'hold')),
    CONSTRAINT ck_news_analyses_price_impact
        CHECK (price_impact_magnitude IS NULL OR price_impact_magnitude IN ('low', 'medium', 'high')),
    CONSTRAINT ck_news_analyses_market_context_status
        CHECK (market_context_status IS NULL OR market_context_status IN ('fresh', 'delayed', 'stale', 'missing')),
    CONSTRAINT ck_news_analyses_validation_status
        CHECK (validation_status IN ('valid', 'rejected'))
);

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS exchange_code TEXT NOT NULL DEFAULT '';

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS strategy TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS direction TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS event_type TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS price_impact_magnitude TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS market_context_status TEXT;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS market_context_as_of TIMESTAMPTZ;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS market_context_snapshot JSONB;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS validation_status TEXT NOT NULL DEFAULT 'valid';

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE thesis_builder.t_news_analyses
    ADD COLUMN IF NOT EXISTS rejection_reason_code TEXT;

CREATE INDEX IF NOT EXISTS ix_news_analyses_article
    ON thesis_builder.t_news_analyses (article_id);

CREATE INDEX IF NOT EXISTS ix_news_analyses_instrument_analyzed
    ON thesis_builder.t_news_analyses (ticker, exchange_code, analyzed_at DESC);

CREATE INDEX IF NOT EXISTS ix_news_analyses_strategy_direction
    ON thesis_builder.t_news_analyses (ticker, exchange_code, strategy, direction, validation_status);

CREATE TABLE IF NOT EXISTS thesis_builder.t_evidence_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    strategy TEXT NOT NULL,
    direction TEXT,
    article_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    analysis_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    window_started_at TIMESTAMPTZ NOT NULL,
    last_evidence_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    status_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_evidence_windows_strategy
        CHECK (
            strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_evidence_windows_direction
        CHECK (direction IS NULL OR direction IN ('buy', 'sell', 'hold')),
    CONSTRAINT ck_evidence_windows_status
        CHECK (status IN ('collecting', 'satisfied', 'expired', 'rejected'))
);

CREATE INDEX IF NOT EXISTS ix_evidence_windows_instrument_status
    ON thesis_builder.t_evidence_windows (ticker, exchange_code, status, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_windows_collecting
    ON thesis_builder.t_evidence_windows (ticker, exchange_code, strategy, COALESCE(direction, ''))
    WHERE status = 'collecting';

CREATE INDEX IF NOT EXISTS ix_evidence_windows_expiry_scan
    ON thesis_builder.t_evidence_windows (status, window_started_at)
    WHERE status = 'collecting';

CREATE TABLE IF NOT EXISTS thesis_builder.t_thesis_cards (
    id TEXT PRIMARY KEY,
    idempotency_key TEXT NOT NULL UNIQUE,
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    direction TEXT NOT NULL,
    time_horizon TEXT NOT NULL,
    strategy TEXT NOT NULL,
    evidence JSONB NOT NULL,
    source_analysis_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence DOUBLE PRECISION NOT NULL,
    risk_max_loss_usd DOUBLE PRECISION NOT NULL,
    risk_stop_condition TEXT NOT NULL,
    risk_invalidation_condition TEXT NOT NULL,
    market_context_status TEXT,
    market_context_as_of TIMESTAMPTZ,
    market_context_snapshot JSONB,
    validation_status TEXT NOT NULL,
    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    signal_published_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_thesis_cards_direction
        CHECK (direction IN ('buy', 'sell', 'hold')),
    CONSTRAINT ck_thesis_cards_strategy
        CHECK (
            strategy IN (
                'event_driven',
                'sentiment_momentum',
                'sector_rotation',
                'contrarian_reversal',
                'trend_follow'
            )
        ),
    CONSTRAINT ck_thesis_cards_confidence
        CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_thesis_cards_risk_max_loss
        CHECK (risk_max_loss_usd >= 0),
    CONSTRAINT ck_thesis_cards_market_context_status
        CHECK (market_context_status IS NULL OR market_context_status IN ('fresh', 'delayed', 'stale', 'missing')),
    CONSTRAINT ck_thesis_cards_validation_status
        CHECK (validation_status IN ('valid', 'rejected'))
);

CREATE INDEX IF NOT EXISTS ix_thesis_cards_instrument_created
    ON thesis_builder.t_thesis_cards (ticker, exchange_code, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_thesis_cards_validation_expiry
    ON thesis_builder.t_thesis_cards (validation_status, expires_at);

CREATE INDEX IF NOT EXISTS ix_thesis_cards_unpublished_valid
    ON thesis_builder.t_thesis_cards (created_at)
    WHERE validation_status = 'valid' AND signal_published_at IS NULL;
