-- AnalyzerWorker physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS analyzer_worker;

CREATE TABLE IF NOT EXISTS analyzer_worker.t_news_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id TEXT NOT NULL REFERENCES news_fetcher.t_news_articles(id),
    ticker TEXT NOT NULL,
    sentiment DOUBLE PRECISION NOT NULL,
    relevance DOUBLE PRECISION NOT NULL,
    urgency TEXT NOT NULL,
    suggested_action TEXT NOT NULL,
    reasoning TEXT,
    confidence DOUBLE PRECISION NOT NULL,
    llm_model TEXT NOT NULL,
    tokens_used BIGINT,
    analyzed_at TIMESTAMPTZ NOT NULL
);
