import pytest

_TRADE_EXECUTOR_ENV = (
    "TRADE_EXECUTOR_DB_SCHEMA", "SHARED_DB_SCHEMA", "MARKET_DATA_DB_SCHEMA", "WATCHLIST_TABLE",
    "TRADE_EXECUTOR_TRADING_MODE", "IBKR_HOST", "IBKR_PORT", "IBKR_TRADE_EXECUTOR_CLIENT_ID",
    "SIGNAL_QUEUE", "TRADE_EXECUTOR_CONSUMER_GROUP", "TRADE_EXECUTOR_CONSUMER_NAME",
    "TRADE_EXECUTOR_BATCH_SIZE", "TRADE_EXECUTOR_BLOCK_MS", "TRADE_EXECUTOR_CLAIM_MIN_IDLE_SECONDS",
    "TRADE_EXECUTOR_MAX_DELIVERY_ATTEMPTS", "TRADE_EXECUTOR_MIN_CONFIDENCE",
    "TRADE_EXECUTOR_QUOTE_MAX_AGE_SECONDS", "ATR_STOP_MULT", "TAKE_PROFIT_R",
    "ENTRY_LIMIT_SLIPPAGE_BPS", "ORDER_FILL_TIMEOUT_SECONDS", "OUTSIDE_RTH",
    "TIME_HORIZON_DAYS_MAP", "TRADING_DAY_TIMEZONE", "MAX_POSITION_SIZE", "MAX_POSITIONS",
    "MAX_PORTFOLIO_EXPOSURE", "MAX_SECTOR_EXPOSURE", "DAILY_LOSS_LIMIT", "MAX_DAILY_TRADES",
    "TRADE_EXECUTOR_POLL_INTERVAL_SECONDS", "TRADE_EXECUTOR_HEARTBEAT_INTERVAL_SECONDS",
)


@pytest.fixture(autouse=True)
def _clean_trade_executor_env(monkeypatch):
    """Give every test the documented defaults unless it sets env explicitly."""
    for key in _TRADE_EXECUTOR_ENV:
        monkeypatch.delenv(key, raising=False)
    yield
