-- MarketData physical schema (PostgreSQL)

CREATE SCHEMA IF NOT EXISTS market_data;

CREATE TABLE IF NOT EXISTS market_data.t_market_provider_symbols (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_symbol TEXT NOT NULL,
    currency TEXT NOT NULL,
    asset_class TEXT NOT NULL DEFAULT 'stock',
    provider_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticker, exchange_code, provider),
    CONSTRAINT ck_market_provider_symbols_provider
        CHECK (provider IN ('ibkr', 'alpha_vantage')),
    CONSTRAINT ck_market_provider_symbols_exchange
        CHECK (exchange_code IN ('XNAS', 'XNYS', 'XETR', 'XPAR')),
    CONSTRAINT ck_market_provider_symbols_asset_class
        CHECK (asset_class IN ('stock', 'etf'))
);

CREATE TABLE IF NOT EXISTS market_data.t_market_quotes (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    provider TEXT NOT NULL,
    data_type TEXT NOT NULL,
    currency TEXT NOT NULL,
    bid_price DOUBLE PRECISION,
    ask_price DOUBLE PRECISION,
    last_price DOUBLE PRECISION,
    previous_close DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    provider_timestamp TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL,
    provider_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (ticker, exchange_code, provider, data_type),
    CONSTRAINT ck_market_quotes_data_type
        CHECK (data_type IN ('realtime', 'delayed', 'frozen', 'stale', 'missing'))
);

CREATE INDEX IF NOT EXISTS ix_market_quotes_instrument_fetched
    ON market_data.t_market_quotes (ticker, exchange_code, fetched_at DESC);

CREATE TABLE IF NOT EXISTS market_data.t_market_bars (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    provider TEXT NOT NULL,
    bar_interval TEXT NOT NULL,
    bar_start_at TIMESTAMPTZ NOT NULL,
    currency TEXT NOT NULL,
    open_price DOUBLE PRECISION NOT NULL,
    high_price DOUBLE PRECISION NOT NULL,
    low_price DOUBLE PRECISION NOT NULL,
    close_price DOUBLE PRECISION NOT NULL,
    volume DOUBLE PRECISION,
    adjusted BOOLEAN NOT NULL DEFAULT FALSE,
    fetched_at TIMESTAMPTZ NOT NULL,
    provider_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (ticker, exchange_code, provider, bar_interval, bar_start_at, adjusted),
    CONSTRAINT ck_market_bars_interval
        CHECK (bar_interval IN ('1m', '5m', '15m', '30m', '1h', '1d'))
);

CREATE INDEX IF NOT EXISTS ix_market_bars_instrument_interval_start
    ON market_data.t_market_bars (ticker, exchange_code, bar_interval, bar_start_at DESC);

CREATE TABLE IF NOT EXISTS market_data.t_market_context_snapshots (
    ticker TEXT NOT NULL,
    exchange_code TEXT NOT NULL,
    as_of TIMESTAMPTZ NOT NULL,
    source_status TEXT NOT NULL,
    current_price DOUBLE PRECISION,
    previous_close DOUBLE PRECISION,
    return_1d DOUBLE PRECISION,
    return_5d DOUBLE PRECISION,
    return_20d DOUBLE PRECISION,
    atr_20d DOUBLE PRECISION,
    volatility_20d DOUBLE PRECISION,
    volume_ratio_20d DOUBLE PRECISION,
    sma_20d DOUBLE PRECISION,
    sma_50d DOUBLE PRECISION,
    recent_high_20d DOUBLE PRECISION,
    recent_low_20d DOUBLE PRECISION,
    drawdown_from_high_20d DOUBLE PRECISION,
    quote_fetched_at TIMESTAMPTZ,
    bars_fetched_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (ticker, exchange_code),
    CONSTRAINT ck_market_context_source_status
        CHECK (source_status IN ('fresh', 'delayed', 'stale', 'missing'))
);

CREATE INDEX IF NOT EXISTS ix_market_context_status_as_of
    ON market_data.t_market_context_snapshots (source_status, as_of DESC);

CREATE TABLE IF NOT EXISTS market_data.t_market_data_fetch_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    operation TEXT NOT NULL,
    ticker TEXT,
    exchange_code TEXT,
    status TEXT NOT NULL,
    error_code TEXT,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_market_data_fetch_runs_status
        CHECK (status IN ('success', 'skipped', 'failed'))
);

CREATE INDEX IF NOT EXISTS ix_market_data_fetch_runs_provider_started
    ON market_data.t_market_data_fetch_runs (provider, started_at DESC);
